### ISSUE TITLE
Error message when the config file is not found is wrong

### ISSUE THREAD

**Issue by keisuke-yanagisawa** [akiyamalab/restretto#13]
@JudeBetow reported the weird error message: `opening grid file failed:testdata/testdata.in`. 

https://github.com/akiyamalab/restretto/blob/master/src/infile_reader.cc#L14

The error message should be `opening config file failed: testdata/testdata.in`.

**Comment by JudeBetow** [comment]
I corrected testdata.in to testgrid.in as suggested, but when I relaunch the code './atomgrid-gen testdata/testgrid.in' I receive the following as message:

'failed to open: testdata/2HU4_A_r.pdbqt'
'Aborted'

**Comment by keisuke-yanagisawa** [comment]
Ah, yes I understand, but I separate the point should be fixed into two parts: error message and error itself.

**Comment by keisuke-yanagisawa** [comment]
The error message has been now fixed. 

> I corrected testdata.in to testgrid.in as suggested, but when I relaunch the code ./atomgrid-gen testdata/testgrid.in I receive the following as message:
> 
> failed to open: testdata/2HU4_A_r.pdbqt
> Aborted

This issue is investigated at #12 now, and thus, this issue is now closed.
