### ISSUE TITLE
The Urgent Code Request for Your Paper named “Large-Scale Membrane Permeability Prediction of Cyclic Peptides Crossing a Lipid Bilayer Based on Enhanced Sampling Molecular Dynamics Simulations”

### ISSUE THREAD

**Issue by caolujing** [akiyamalab/restretto#15]
I apologize for interrupting your busy schedule. I am a graduate student focusing on related research about cyclic peptides. Now I have a paper under review, and my reviewer recommends using your model as comparison (entitle "Large-Scale Membrane Permeability Prediction of Cyclic Peptides Crossing a Lipid Bilayer Based on Enhanced Sampling Molecular Dynamics Simulations"). However, I find this work cannot be accessible to any open-source platforms such as GitHub. Therefore, I am writing to inquire if you would be willing to share the source program, dataset, and any necessary information related to your study. I assure you that these materials will be used solely for research purposes, and I will fully cite and acknowledge your work in any of my publications.

I would greatly appreciate your assistance and guidance in this matter. Thank you very much for your kind consideration and I am looking forward to your early reply.

**Comment by keisuke-yanagisawa** [comment]
Here is REstretto repository, not related to cyclic peptide.
